"""Generate portable figures and a results note from actual experiment outputs."""
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


def write_report(summary, policies, output, synthetic=True):
    plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 10,
                         "axes.spines.top": False, "axes.spines.right": False})
    colors = ["#94a3b8", "#0d9488"]
    labels = [s.replace("_", "\n").title() for s in summary.scenario]
    x = np.arange(len(labels))
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.8), facecolor="#f8fafc")
    for ax in axes:
        ax.set_facecolor("#f8fafc")
        ax.grid(axis="y", alpha=.15)
        ax.set_axisbelow(True)
    for k, (name, title) in enumerate([("independent", "Independent"), ("coordinated", "Coordinated")]):
        axes[0].bar(x + (k - .5) * .34, summary[f"{name}_cost"], .34, color=colors[k], label=title)
        axes[1].bar(x + (k - .5) * .34, summary[f"{name}_fill"] * 100, .34, color=colors[k])
    axes[0].set_ylabel("Cost units / day · lower is better")
    axes[1].set_ylabel("Immediate unit fill rate (%) · higher is better")
    axes[1].set_ylim(0, 105)
    for ax in axes:
        ax.set_xticks(x, labels)
    axes[0].legend(frameon=False)
    fig.suptitle("Inventory decisions under uncertainty", x=.07, ha="left", fontsize=19, weight="bold")
    source_label = "Synthetic demand" if synthetic else "User-supplied demand"
    fig.text(.07, .90, source_label + " • held-out simulation seeds • identical demand paths per policy", color="#475569")
    fig.tight_layout(rect=[0, 0, 1, .87])
    fig.savefig(output / "policy_comparison.png", dpi=180)
    plt.close(fig)
    lines = ["# Experiment results", "", "Generated by the repository CLI. All inputs are synthetic; costs are arbitrary cost units.", "",
             "| Scenario | Independent cost/day | Coordinated cost/day | Cost saving | Independent fill | Coordinated fill | 95% CI, saving/day |",
             "|---|---:|---:|---:|---:|---:|---:|"]
    for r in summary.itertuples():
        lines.append(f"| {r.scenario} | {r.independent_cost:.2f} | {r.coordinated_cost:.2f} | {r.saving_pct:.1f}% | {r.independent_fill:.1%} | {r.coordinated_fill:.1%} | [{r.saving_ci95_low:.2f}, {r.saving_ci95_high:.2f}] |")
    lines += ["", "Positive savings favor coordinated targets; negative values favor independent targets.",
              "Confidence intervals describe simulation-seed uncertainty, conditional on this fitted model.",
              "They do not capture model misspecification or uncertainty in the historical sample.", "", "## Stock targets", "", "| Policy | Warehouse 0 | Store 1 | Store 2 |", "|---|---:|---:|---:|"]
    for name, targets in policies.items():
        lines.append(f"| {name} | {targets[0]} | {targets[1]} | {targets[2]} |")
    lines += ["", "![Policy comparison](policy_comparison.png)", ""]
    (output / "RESULTS.md").write_text("\n".join(lines))
